CREATE DATABASE IF NOT EXISTS hue CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER IF NOT EXISTS 'hue'@'%' IDENTIFIED BY 'secret';
ALTER USER 'hue'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON hue.* TO 'hue'@'%';
FLUSH PRIVILEGES;
