docker.sources = spool-source
docker.sinks = kafka-sink
docker.channels = memory-channel

# ---- Source: يراقب فولدر الـ RetailPulse ويقرأ كل ملف سطر-سطر (كل سطر = حدث JSON) ----
docker.sources.spool-source.type = spooldir
docker.sources.spool-source.spoolDir = /var/log/flume_lab/retailpulse
docker.sources.spool-source.fileHeader = false
docker.sources.spool-source.deserializer = LINE
docker.sources.spool-source.deserializer.maxLineLength = 8192
docker.sources.spool-source.batchSize = 1000
docker.sources.spool-source.channels = memory-channel

# ---- Channel ----
docker.channels.memory-channel.type = memory
docker.channels.memory-channel.capacity = 20000
docker.channels.memory-channel.transactionCapacity = 2000

# ---- Sink: Kafka ----
docker.sinks.kafka-sink.type = org.apache.flume.sink.kafka.KafkaSink
docker.sinks.kafka-sink.kafka.bootstrap.servers = kafka:9092
docker.sinks.kafka-sink.kafka.topic = retail_logs
docker.sinks.kafka-sink.kafka.flumeBatchSize = 1000
docker.sinks.kafka-sink.kafka.producer.acks = 1
docker.sinks.kafka-sink.kafka.producer.compression.type = snappy
docker.sinks.kafka-sink.useFlumeEventFormat = false
docker.sinks.kafka-sink.channel = memory-channel